#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileAds.Droid.Resource", IsApplication=true)]

namespace MobileAds.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hd_wallpaper = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int ContentParentLayout = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int wbCloseButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int wbPostContent = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int webview = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContentLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PostLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int MSG_ERROR = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int MSG_EXIT = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int MSG_NO_NETWORK = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int MSG_TRY_AGAIN = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int URL_ADS_MANAGER = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int URL_SIMPLE_API = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int URL_WP_API = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int WP_CATEGORIES = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
